repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10000']

  - repo: https://github.com/ow-gryphon/gryphon-pre-commit-hooks
    rev: 0.1.0
    hooks:
      - id: ignore-files
